base_config: ../config/
base_expid: AFN_criteo_x4
dataset_id: criteo_x4_001_be98441d

dataset_config:
    criteo_x4_001_be98441d:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_001_be98441d/train.h5
        valid_data: ../data/Criteo/criteo_x4_001_be98441d/valid.h5
        test_data: ../data/Criteo/criteo_x4_001_be98441d/test.h5

tuner_space:
    model_root: './Criteo/AFN_criteo/'
    embedding_regularizer: [1.e-5, 5.e-6, 1.e-6]
    batch_size: 2000
    embedding_dim: 40
    logarithmic_neurons: [800, 1200, 1500]
    afn_hidden_units: [[1000, 1000], [1000, 1000, 1000], [2000, 2000, 2000]]
    afn_activations: relu
    afn_dropout: [0, 0.1, 0.2]
    ensemble_dnn: False
    dnn_hidden_units: [[]]
    dnn_activations: relu
    dnn_dropout: 0
    batch_norm: True
    seed: 2019

