base_config: ../config/
base_setting: PNN_avazu_x4

tuner_space:
    model_dir: './PNN_avazu/'
    min_categr_count: 1
    seed: 2019
    dropout_rates: [0, 0.1, 0.2]
    embedding_regularizer: [0, 'l2(1.e-8)']
    batch_size: 10000
    hidden_units: [[300, 300, 300], [400, 400, 400], [500, 500, 500]]
    layer_norm: [False, True]

             

