xDeepFM_kkbox_x1_001_5a97f058:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [10, 10]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_002_22629b2b:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [10, 10]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_003_38d22342:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [10, 10]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_004_20b5da2c:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [13, 13]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_005_761225af:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [13, 13]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_006_9bc90848:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [13, 13]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_007_49197bdf:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [16, 16]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_008_e312d576:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [16, 16]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_009_a9bd7928:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [16, 16]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_010_d6468436:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [32, 32]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_011_935d7b7d:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [32, 32]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_012_21b4b61a:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [32, 32]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_013_80171ac0:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [10, 10, 10]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_014_dacdde39:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [10, 10, 10]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_015_d2c15446:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [10, 10, 10]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_016_3f7730bd:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [13, 13, 13]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_017_6056fbb1:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [13, 13, 13]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_018_10ee2eb5:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [13, 13, 13]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_019_f91b5033:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [16, 16, 16]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_020_b45def28:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [16, 16, 16]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
xDeepFM_kkbox_x1_021_b608a4a1:
    batch_norm: false
    batch_size: 10000
    cin_layer_units: [16, 16, 16]
    dataset_id: kkbox_x1_227d337d
    debug: false
    dnn_hidden_units: [5000, 5000]
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./KKBox/xDeepFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
