base_config: ../config/
base_expid: FFM_base
dataset_id: criteo_x4_5c863b0f

dataset_config:
    criteo_x4_5c863b0f:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_5c863b0f/train.h5
        valid_data: ../data/Criteo/criteo_x4_5c863b0f/valid.h5
        test_data: ../data/Criteo/criteo_x4_5c863b0f/test.h5

tuner_space:
    model_root: './Criteo/FFM_criteo/min10/'
    embedding_dim: [4, 8, 16]
    regularizer: [0, 1.e-8, 1.e-7, 1.e-6]
    batch_size: 10000
    learning_rate: 1.e-3
    seed: 2019
