base_config: ../config/
base_expid: FiGNN_kkbox_x4

dataset_config:
    kkbox_x4_001_c5c9c6e3:
        data_format: h5
        data_root: '../data/KKBox/'
        train_data: ../data/KKBox/kkbox_x4_001_c5c9c6e3/train.h5
        valid_data: ../data/KKBox/kkbox_x4_001_c5c9c6e3/valid.h5
        test_data: ../data/KKBox/kkbox_x4_001_c5c9c6e3/test.h5

tuner_space:
    model_root: './KKBox/FiGNN_kkbox/'
    embedding_dim: 128
    learning_rate: 1.e-3
    embedding_regularizer: [1.e-4, 5.e-4]
    gnn_layers: [2, 3]
    use_residual: [True, False]
    use_gru: [True, False]
    reuse_graph_layer: False
    batch_size: 2000
    seed: 2019
