xDeepFM_avazu_x1_013_667f616d:
    batch_norm: false
    batch_size: 4096
    cin_layer_units: [32, 32, 32]
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1