FiGNN_kkbox_x1_001_2a31541f:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_kkbox_x1_002_073bb66c:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_kkbox_x1_003_5054bb1e:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: false
    verbose: 1
    workers: 3
FiGNN_kkbox_x1_004_07ac98c3:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: false
    verbose: 1
    workers: 3
FiGNN_kkbox_x1_005_38f02f9a:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_kkbox_x1_006_f823e03f:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_kkbox_x1_007_1b6911cd:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: false
    verbose: 1
    workers: 3
FiGNN_kkbox_x1_008_0d060af8:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: false
    verbose: 1
    workers: 3
FiGNN_kkbox_x1_009_eb83633e:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_kkbox_x1_010_28e80cb6:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_kkbox_x1_011_69e1be4c:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: false
    verbose: 1
    workers: 3
FiGNN_kkbox_x1_012_5849f9b1:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: false
    verbose: 1
    workers: 3
FiGNN_kkbox_x1_013_1ab3ffcd:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_kkbox_x1_014_506530b4:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: true
    verbose: 1
    workers: 3
FiGNN_kkbox_x1_015_62ca0ccc:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: true
    use_hdf5: true
    use_residual: false
    verbose: 1
    workers: 3
FiGNN_kkbox_x1_016_9229c5c8:
    batch_size: 2000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    gnn_layers: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FiGNN
    model_id: FiGNN_base
    model_root: ./KKBox/FiGNN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    reuse_graph_layer: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_gru: false
    use_hdf5: true
    use_residual: false
    verbose: 1
    workers: 3
