base_config: ../config/
base_expid: FiGNN_criteo_x4
dataset_id: criteo_x4_001_be98441d

dataset_config:
    criteo_x4_001_be98441d:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_001_be98441d/train.h5
        valid_data: ../data/Criteo/criteo_x4_001_be98441d/valid.h5
        test_data: ../data/Criteo/criteo_x4_001_be98441d/test.h5

tuner_space:
    model_root: './Criteo/FiGNN_criteo/'
    embedding_dim: 40
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-5
    net_regularizer: 0
    gnn_layers: [4, 3, 2]
    use_residual: [True, False]
    use_gru: [True, False]
    reuse_graph_layer: False
    batch_size: 5000
    seed: 2019
