MaskNet_avazu_x1_001_79b76de2:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: true
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Avazu/MaskNet_avazu_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 1
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
MaskNet_avazu_x1_002_fa7aa0a6:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: true
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Avazu/MaskNet_avazu_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 1
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
MaskNet_avazu_x1_003_d839526a:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Avazu/MaskNet_avazu_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 1
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
MaskNet_avazu_x1_004_61f3fe11:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Avazu/MaskNet_avazu_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 1
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
MaskNet_avazu_x1_005_d73d1a33:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: true
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Avazu/MaskNet_avazu_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 1
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
MaskNet_avazu_x1_006_85019ef5:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: true
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Avazu/MaskNet_avazu_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 1
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
MaskNet_avazu_x1_007_435f5397:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Avazu/MaskNet_avazu_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 1
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
MaskNet_avazu_x1_008_a987e03d:
    batch_size: 4096
    data_block_size: -1
    dataset_id: avazu_x1_3fb65689
    debug: false
    dnn_hidden_activations: relu
    dnn_hidden_units: [400, 400, 400]
    emb_layernorm: false
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: MaskNet
    model_id: MaskNet_base
    model_root: ./Avazu/MaskNet_avazu_x1/
    model_type: SerialMaskNet
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_layernorm: true
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    parallel_block_dim: 64
    parallel_num_blocks: 1
    patience: 2
    pickle_feature_encoder: true
    reduction_ratio: 1
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
