base_config: ../config/
base_expid: xDeepFM_base
dataset_id: avazu_x4_3bbbc4c9

dataset_config:
    avazu_x4_3bbbc4c9:
        data_format: h5
        data_root: '../data/Avazu/'
        train_data: ../data/Avazu/avazu_x4_3bbbc4c9/train.h5
        valid_data: ../data/Avazu/avazu_x4_3bbbc4c9/valid.h5
        test_data: ../data/Avazu/avazu_x4_3bbbc4c9/test.h5

tuner_space:
    model_root: './Avazu/xDeepFM_avazu/min2/CIN_avazu/'
    embedding_dim: 16
    learning_rate: 1.e-3
    dnn_hidden_units: [[]]
    cin_layer_units: [[200, 200, 200, 200, 200], [200, 200, 200, 200, 200, 200]]
    net_dropout: 0
    embedding_regularizer: 0
    batch_size: 5000
    seed: 2019
