base_config: ../config/
base_expid: CCPM_criteo_x4
dataset_id: criteo_x4_001_be98441d

dataset_config:
    criteo_x4_001_be98441d:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_001_be98441d/train.h5
        valid_data: ../data/Criteo/criteo_x4_001_be98441d/valid.h5
        test_data: ../data/Criteo/criteo_x4_001_be98441d/test.h5

tuner_space:
    model_root: './Criteo/CCPM_criteo/'
    embedding_dim: 40
    embedding_regularizer: [0, 1.e-8]
    batch_size: 5000
    learning_rate: 1.e-3
    channels: [[64, 128, 256], [128, 256, 512]]
    kernel_heights: [[3, 3, 3], [5, 5, 5], [7, 7, 7], [7, 5, 3]]
    seed: 2019
   
