base_config: ../config/
base_expid: LorentzFM_avazu_x4

dataset_config:
    avazu_x4_001_d45ad60e:
        data_format: h5
        data_root: '../data/Avazu/'
        train_data: ../data/Avazu/avazu_x4_001_d45ad60e/train.h5
        valid_data: ../data/Avazu/avazu_x4_001_d45ad60e/valid.h5
        test_data: ../data/Avazu/avazu_x4_001_d45ad60e/test.h5

tuner_space:
    model_root: './Avazu/LorentzFM_avazu/'
    embedding_dim: 40
    regularizer: ['l2(1.e-6)', 'l2(1.e-7)', 'l2(1.e-8)', 'l2(1.e-9)', 0]
    learning_rate: 1.e-3
    batch_size: 10000
    seed: 2019


