base_config: ../config/
base_expid: ONN_avazu_x4

dataset_config:
    avazu_x4_001_d45ad60e:
        data_format: h5
        data_root: '../data/Avazu/'
        train_data: ../data/Avazu/avazu_x4_001_d45ad60e/train.h5
        valid_data: ../data/Avazu/avazu_x4_001_d45ad60e/valid.h5
        test_data: ../data/Avazu/avazu_x4_001_d45ad60e/test.h5

tuner_space:
    model_root: './Avazu/ONN_avazu/'
    embedding_dim: 2
    learning_rate: 1.e-3
    hidden_units: [[1000, 1000, 1000, 1000, 1000], [3000, 3000, 3000, 3000, 3000],
                   [1000, 1000, 1000, 1000, 1000, 1000], [3000, 3000, 3000, 3000, 3000, 3000]]
    net_dropout: [0.2, 0]
    embedding_regularizer: ['l2(1.e-8)', 'l2(1.e-6)', 0]
    batch_size: 10000
    seed: 2019
    batch_norm: [False, True]
