base_config: ../config/
base_expid: DCN_base
dataset_id: criteo_x4_5c863b0f

dataset_config:
    criteo_x4_5c863b0f:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_5c863b0f/train.h5
        valid_data: ../data/Criteo/criteo_x4_5c863b0f/valid.h5
        test_data: ../data/Criteo/criteo_x4_5c863b0f/test.h5

tuner_space:
    model_root: './Criteo/DCN_criteo/min10/'
    embedding_dim: 16
    embedding_regularizer: [1.e-5, 1.e-4]
    dnn_hidden_units: [[500, 500, 500, 500], [500, 500, 500, 500, 500], [1000, 1000, 1000, 1000], [1000, 1000, 1000, 1000, 1000]]
    crossing_layers: 4
    net_dropout: [0, 0.1, 0.2]
    learning_rate: 1.e-3
    batch_size: 10000
    seed: 2019