AutoInt_frappe_x1_001_87d22ad5:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_frappe_x1_002_00a687b1:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: false
    verbose: 1
AutoInt_frappe_x1_003_ae71ebc0:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: false
    use_wide: true
    verbose: 1
AutoInt_frappe_x1_004_bf64c3c6:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: false
    use_wide: false
    verbose: 1
AutoInt_frappe_x1_005_d82324a9:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_frappe_x1_006_035c3582:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: true
    use_wide: false
    verbose: 1
AutoInt_frappe_x1_007_ffcddcb7:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: false
    use_wide: true
    verbose: 1
AutoInt_frappe_x1_008_a05414ad:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: true
    use_scale: false
    use_wide: false
    verbose: 1
AutoInt_frappe_x1_009_58a93cb3:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: false
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_frappe_x1_010_330e3f94:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: false
    use_scale: true
    use_wide: false
    verbose: 1
AutoInt_frappe_x1_011_ff974f13:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: false
    use_scale: false
    use_wide: true
    verbose: 1
AutoInt_frappe_x1_012_61ec6bf4:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: true
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: false
    use_scale: false
    use_wide: false
    verbose: 1
AutoInt_frappe_x1_013_55423b20:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: false
    use_scale: true
    use_wide: true
    verbose: 1
AutoInt_frappe_x1_014_a4ced2ad:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: false
    use_scale: true
    use_wide: false
    verbose: 1
AutoInt_frappe_x1_015_f5a59a7b:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: false
    use_scale: false
    use_wide: true
    verbose: 1
AutoInt_frappe_x1_016_94b81c18:
    attention_dim: 128
    attention_layers: 5
    batch_norm: true
    batch_size: 4096
    dataset_id: frappe_x1_04e961e9
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    layer_norm: false
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: AutoInt
    model_id: AutoInt_base
    model_root: ./Frappe/AutoInt_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    use_residual: false
    use_scale: false
    use_wide: false
    verbose: 1
