base_config: ../config/
base_expid: xDeepFM_kkbox_x4

dataset_config:
    kkbox_x4_001_c5c9c6e3:
        data_format: h5
        data_root: '../data/KKBox/'
        train_data: ../data/KKBox/kkbox_x4_001_c5c9c6e3/train.h5
        valid_data: ../data/KKBox/kkbox_x4_001_c5c9c6e3/valid.h5
        test_data: ../data/KKBox/kkbox_x4_001_c5c9c6e3/test.h5

tuner_space:
    model_root: './KKBox/CIN_kkbox/'
    embedding_dim: 128
    dnn_hidden_units: [[]]
    cin_layer_units: [[64, 64], [64, 64, 64], [78, 78], [78, 78, 78], [78, 78, 78, 78]]
    embedding_regularizer: [1.e-6, 1.e-5, 1.e-4]
    net_dropout: [0, 0.2, 0.3]
    learning_rate: 0.001
    batch_size: 5000
    seed: 2019
