base_config: ../config/
base_expid: FiBiNET_base
dataset_id: avazu_x4_3bbbc4c9

dataset_config:
    avazu_x4_3bbbc4c9:
        data_format: h5
        data_root: '../data/Avazu/'
        train_data: ../data/Avazu/avazu_x4_3bbbc4c9/train.h5
        valid_data: ../data/Avazu/avazu_x4_3bbbc4c9/valid.h5
        test_data: ../data/Avazu/avazu_x4_3bbbc4c9/test.h5

tuner_space:
    model_root: './Avazu/FiBiNET_avazu/min2/'
    embedding_dim: 16
    learning_rate: 1.e-3
    embedding_regularizer: [0, 1.e-8, 1.e-9]
    net_dropout: [0, 0.1, 0.2]
    hidden_units: [[2000, 2000, 2000], [1000, 1000, 1000, 1000], [2000, 2000, 2000, 2000], [5000, 2000, 1000]]
    bilinear_type: "field_interaction"
    batch_size: 10000
    seed: 2019
    

