base_config: ../config/
base_expid: FiBiNET_base
dataset_id: criteo_x4_9ea3bdfc

dataset_config:
    criteo_x4_9ea3bdfc:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_9ea3bdfc/train.h5
        valid_data: ../data/Criteo/criteo_x4_9ea3bdfc/valid.h5
        test_data: ../data/Criteo/criteo_x4_9ea3bdfc/test.h5

tuner_space:
    model_root: './Criteo/FiBiNET_criteo_x4_001/'
    learning_rate: 1.e-3
    embedding_dim: 16
    embedding_regularizer: [1.e-6, 5.e-6, 5.e-7]
    batch_size: 10000
    hidden_units: [[2000, 2000, 2000, 2000], [2000, 2000, 2000]]
    net_dropout: [0, 0.1, 0.2]
    reduction_ratio: 3
    batch_norm: False
    bilinear_type: "field_interaction"
    seed: 2019

