base_config: ../config/
base_expid: FiGNN_base
dataset_id: criteo_x4_9ea3bdfc

dataset_config:
    criteo_x4_9ea3bdfc:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_9ea3bdfc/train.h5
        valid_data: ../data/Criteo/criteo_x4_9ea3bdfc/valid.h5
        test_data: ../data/Criteo/criteo_x4_9ea3bdfc/test.h5

tuner_space:
    model_root: './Criteo/FiGNN_criteo/min10/'
    embedding_dim: 16
    learning_rate: 1.e-3
    embedding_regularizer: [1.e-6, 1.e-5, 1.e-4]
    net_regularizer: 0
    gnn_layers: [5, 4, 3, 2]
    use_residual: True
    use_gru: True
    reuse_graph_layer: False
    batch_size: 10000
    seed: 2019
