base_config: ../config/
base_expid: AutoInt_base
dataset_id: criteo_x4_9ea3bdfc

dataset_config:
    criteo_x4_9ea3bdfc:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_9ea3bdfc/train.h5
        valid_data: ../data/Criteo/criteo_x4_9ea3bdfc/valid.h5
        test_data: ../data/Criteo/criteo_x4_9ea3bdfc/test.h5

tuner_space:
    model_root: './Criteo/AutoInt_criteo/min10/'
    embedding_dim: 16
    learning_rate: 1.e-3
    dnn_hidden_units: [[1000, 1000, 1000], [1000, 1000, 1000, 1000], [1000, 1000, 1000, 1000, 1000]]
    embedding_regularizer: [1.e-5, 1.e-6, 1.e-7]
    net_dropout: 0
    num_heads: 1
    attention_layers: [3, 4, 5]
    attention_dim: 64
    use_residual: True
    batch_norm: False
    layer_norm: False
    use_scale: False
    use_wide: True
    batch_size: 10000
    seed: 2019

