base_config: ../config/
base_expid: DeepFM_avazu_x4

dataset_config:
    avazu_x4_001_d45ad60e:
        data_format: h5
        data_root: '../data/Avazu/'
        train_data: ../data/Avazu/avazu_x4_001_d45ad60e/train.h5
        valid_data: ../data/Avazu/avazu_x4_001_d45ad60e/valid.h5
        test_data: ../data/Avazu/avazu_x4_001_d45ad60e/test.h5

tuner_space:
    model_root: './Avazu/DeepFM_avazu/'
    learning_rate: 1.e-3
    embedding_dim: 40
    hidden_units: [[3000, 3000, 3000, 3000]]
    net_dropout: 0
    embedding_regularizer: 0
    batch_size: 10000
    seed: [658895, 382107, 2019]
