base_config: ../config/
base_expid: DeepFM_criteo_x4

dataset_config:
    criteo_x4_001_be98441d:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_001_be98441d/train.h5
        valid_data: ../data/Criteo/criteo_x4_001_be98441d/valid.h5
        test_data: ../data/Criteo/criteo_x4_001_be98441d/test.h5

tuner_space:
    model_root: './Criteo/DeepFM_criteo/'
    embedding_dim: 40
    learning_rate: 1.e-3
    hidden_units: [[1000, 1000, 1000], [2000, 2000, 2000], 
                   [500, 500, 500, 500], [1000, 1000, 1000, 1000]]
    net_dropout: [0, 0.1, 0.2]
    embedding_regularizer: ['l2(1.e-6)', 'l2(1.e-5)']
    batch_size: 10000
    seed: 2019
    batch_norm: [False, True]
