base_config: ../config/
base_expid: ONN_base
dataset_id: criteo_x4_9ea3bdfc

dataset_config:
    criteo_x4_9ea3bdfc:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_9ea3bdfc/train.h5
        valid_data: ../data/Criteo/criteo_x4_9ea3bdfc/valid.h5
        test_data: ../data/Criteo/criteo_x4_9ea3bdfc/test.h5

tuner_space:
    model_root: './Criteo/ONN_criteo/min10/'
    embedding_dim: 8
    learning_rate: 1.e-3
    hidden_units: [[1000, 1000, 1000]]
    net_dropout: [0.3, 0.4, 0.5]
    embedding_regularizer: 1.e-5
    batch_size: 10000
    seed: 2019
