EDCN_movielenslatest_x1_001_3029c8f4:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_002_f6a0e46b:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_cross_layers: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_003_be82e279:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    num_cross_layers: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_004_174d2777:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 5
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_005_ca9beca1:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_cross_layers: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 5
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_006_3d9258c8:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    num_cross_layers: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 5
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_007_893f08cd:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_008_af0b9657:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_cross_layers: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_009_066c12db:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    num_cross_layers: 2
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_010_e5cb2f75:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_011_778c7157:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_012_f1bb7b0e:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_013_21a2eed4:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 5
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_014_58fba97b:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 5
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_015_3901efd7:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 5
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_016_13cc13bb:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_017_3e7dc26d:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.4
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
EDCN_movielenslatest_x1_018_e6a012c5:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: movielenslatest_x1_cd32d937
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Movielens/EDCN_movielenslatest_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.5
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 1
