base_config: ../config/
base_expid: xDeepFM_avazu_x4

dataset_config:
    avazu_x4_001_d45ad60e:
        data_format: h5
        data_root: '../data/Avazu/'
        train_data: ../data/Avazu/avazu_x4_001_d45ad60e/train.h5
        valid_data: ../data/Avazu/avazu_x4_001_d45ad60e/valid.h5
        test_data: ../data/Avazu/avazu_x4_001_d45ad60e/test.h5

tuner_space:
    model_root: './Avazu/xDeepFM_avazu/'
    embedding_dim: 40
    learning_rate: 1.e-3
    dnn_hidden_units: [[200, 200], [500, 500], [1000, 1000], [500, 500, 500]]
    cin_layer_units: [[50, 50], [50, 50, 50]]
    net_dropout: [0, 0.1, 0.2]
    embedding_regularizer: 0
    batch_size: 10000
    seed: 2019
    batch_norm: False
