base_config: ../config/
base_expid: HFM_avazu_x4

dataset_config:
    avazu_x4_001_d45ad60e:
        data_format: h5
        data_root: '../data/Avazu/'
        train_data: ../data/Avazu/avazu_x4_001_d45ad60e/train.h5
        valid_data: ../data/Avazu/avazu_x4_001_d45ad60e/valid.h5
        test_data: ../data/Avazu/avazu_x4_001_d45ad60e/test.h5

tuner_space:
    model_root: './Avazu/HFM_avazu/'
    embedding_dim: 40
    use_dnn: True
    interaction_type: 'circular_correlation'
    embedding_regularizer: [0, 1.e-9]
    hidden_units: [[1000, 1000], [2000, 2000], [1000, 1000, 1000], [1000, 1000, 1000, 1000], 
                   [500, 500]]
    learning_rate: 1.e-3
    net_dropout: [0, 0.1, 0.2]
    batch_size: 5000
    seed: 2019


