base_config: ../config/
base_expid: DCN_base
dataset_id: avazu_x4_3bbbc4c9

dataset_config:
    avazu_x4_3bbbc4c9:
        data_format: h5
        data_root: '../data/Avazu/'
        train_data: ../data/Avazu/avazu_x4_3bbbc4c9/train.h5
        valid_data: ../data/Avazu/avazu_x4_3bbbc4c9/valid.h5
        test_data: ../data/Avazu/avazu_x4_3bbbc4c9/test.h5

tuner_space:
    model_root: './Avazu/DCN_avazu/min2/'
    embedding_dim: 16
    embedding_regularizer: [0, 1.e-8, 1.e-7]
    dnn_hidden_units: [[2000, 2000, 2000], [5000, 2000, 1000], [5000, 2000, 1000, 500], [2000, 2000, 2000, 2000], [2000, 2000, 2000, 2000, 2000]]
    crossing_layers: [1, 2, 3]
    learning_rate: 1.e-3
    net_dropout: 0
    batch_size: 10000
    seed: 2019
