base_config: ../config/
base_setting: FFM_criteo_x4

tuner_space:
    model_dir: './Criteo/'
    min_categr_count: 2
    embedding_dim: [1, 2, 3, 4, 5]
    regularizer: [0, 1.e-9, 1.e-8, 1.e-7, 1.e-6]
    batch_size: 10000
    learning_rate: [1.e-3, 1.e-4]
    seed: 2019
