base_config: ../config/
base_expid: FiGNN_avazu_x4

tuner_space:
    data_root: '../data/Avazu/'
    model_root: './Avazu/FiGNN_avazu/'
    min_categr_count: 1
    embedding_dim: 40
    learning_rate: 1.e-3
    embedding_regularizer: [0, 1.e-8]
    net_regularizer: 0
    gnn_layers: [5, 6, 7, 8, 10]
    use_residual: True
    use_gru: True
    reuse_graph_layer: True
    batch_size: 2000
    seed: 2019
