base_config: ../config/
base_expid: FGCNN_base
dataset_id: avazu_x4_3bbbc4c9

dataset_config:
    avazu_x4_3bbbc4c9:
        data_format: h5
        data_root: '../data/Avazu/'
        train_data: ../data/Avazu/avazu_x4_3bbbc4c9/train.h5
        valid_data: ../data/Avazu/avazu_x4_3bbbc4c9/valid.h5
        test_data: ../data/Avazu/avazu_x4_3bbbc4c9/test.h5

tuner_space:
    model_root: './Avazu/FGCNN_avazu/min2/'
    embedding_dim: 16
    share_embedding: False
    embedding_regularizer: [0, 1.e-9]
    net_dropout: 0
    channels: [[20, 22, 24, 26], [26, 28, 30, 32], [32, 34, 36, 38], [38, 40, 42, 44]]
    kernel_heights: [[9, 9, 9, 9]]
    pooling_sizes: [[2, 2, 2, 2]]
    recombined_channels: [[3, 3, 3, 3]]
    conv_activation: Tanh
    conv_batch_norm: True
    dnn_hidden_units: [[1000, 1000, 1000, 1000], [2000, 2000, 2000, 2000]]
    dnn_batch_norm: False
    learning_rate: 1.e-3
    batch_size: 10000
    seed: 2019