EDCN_criteo_x1_001_9080a6e6:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_002_02f833ca:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_003_f91d8def:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_004_03322833:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 5
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_005_5065d102:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 5
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_006_fd4dc20c:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 5
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_007_fd9990ce:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_008_719275a5:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_009_55bb2f23:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 4
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_010_51bef276:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_011_c725b2b1:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_012_d7c46c3d:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 1
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_013_8ef541ec:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 5
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_014_813059f6:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 5
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_015_bb733d5a:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 5
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_016_2e06fd04:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_cross_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_017_b29ec815:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
EDCN_criteo_x1_018_6ef51cfd:
    batch_norm: true
    batch_size: 4096
    bridge_type: hadamard_product
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: ReLU
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: EDCN
    model_id: EDCN_base
    model_root: ./Criteo/EDCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 5
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    temperature: 10
    use_hdf5: true
    use_regulation_module: true
    verbose: 0
