base_config: ../config/
base_setting: DNN_criteo_x4

tuner_space:
    model_dir: './Criteo/'
    min_categr_count: 2
    embedding_dim: 40
    learning_rate: 1.e-3
    batch_size: 10000
    seed: 2019
    dropout_rates: [0, 0.1]
    embedding_regularizer: [0, 'l2(1.e-7)', 'l2(1.e-8)', 'l2(1.e-9)']
    hidden_units: [[300, 300, 300], [500, 500, 500], [700, 700, 700], [1000, 1000, 1000],
                   [300, 300, 300, 300], [500, 500, 500, 500], [700, 700, 700, 700], [1000, 1000, 1000, 1000]]
    batch_norm: False
