base_config: ../config/
base_expid: InterHAt_base
dataset_id: criteo_x4_9ea3bdfc

dataset_config:
    criteo_x4_9ea3bdfc:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_9ea3bdfc/train.h5
        valid_data: ../data/Criteo/criteo_x4_9ea3bdfc/valid.h5
        test_data: ../data/Criteo/criteo_x4_9ea3bdfc/test.h5

tuner_space:
    model_root: './Criteo/InterHAt_criteo/min10/'
    embedding_dim: 16
    learning_rate: 1.e-3
    order: 2
    num_heads: [1, 2, 4]
    attention_dim: 16
    hidden_dim: [500, 128, 64]
    hidden_units: [[1000, 1000]]
    net_dropout: 0
    embedding_regularizer: [1.e-5, 1.e-4]
    layer_norm: [True, False]
    use_residual: [True, False]
    batch_size: 10000
    seed: 2019
