base_config: ../config/
base_expid: CCPM_base
dataset_id: avazu_x4_3bbbc4c9

dataset_config:
    avazu_x4_3bbbc4c9:
        data_format: h5
        data_root: '../data/Avazu/'
        train_data: ../data/Avazu/avazu_x4_3bbbc4c9/train.h5
        valid_data: ../data/Avazu/avazu_x4_3bbbc4c9/valid.h5
        test_data: ../data/Avazu/avazu_x4_3bbbc4c9/test.h5

tuner_space:
    model_root: './Avazu/CCPM_avazu/min2/'
    embedding_dim: 16
    embedding_regularizer: [0, 1.e-8]
    learning_rate: 1.e-3
    channels: [[16, 32, 64], [32, 64, 128], [64, 128, 256], [128, 256, 512], [256, 512, 1024]]
    kernel_heights: [[7, 5, 3]]
    activation: [Tanh, ReLU]
    batch_size: 10000
    seed: 2019
