base_config: ../config/
base_expid: AutoInt_criteo_x4
dataset_id: criteo_x4_001_be98441d

dataset_config:
    criteo_x4_001_be98441d:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_001_be98441d/train.h5
        valid_data: ../data/Criteo/criteo_x4_001_be98441d/valid.h5
        test_data: ../data/Criteo/criteo_x4_001_be98441d/test.h5

tuner_space:
    model_root: './Criteo/AutoInt_criteo/'
    embedding_dim: 40
    learning_rate: 1.e-3
    dnn_hidden_units: [[]]
    embedding_regularizer: [1.e-5, 1.e-6]
    net_dropout: 0
    num_heads: [1, 2]
    attention_layers: [1, 2, 3, 4, 5]
    attention_dim: [40, 80, 20]
    use_residual: True
    batch_norm: False
    layer_norm: False
    use_scale: False
    use_wide: [True, False]
    batch_size: 10000
    seed: 2019
