base_config: ../config/
base_expid: AFM_avazu_x4

tuner_space:
    model_root: './Avazu/AFM_avazu/'
    min_categr_count: 1
    seed: 2019
    embedding_regularizer: [1.e-7, 1.e-6, 0]
    net_regularizer: [1.e-7, 1.e-6, 0]
    batch_size: 10000
    embedding_dim: 40
    attention_dim: 40
    attention_dropout: [0.2, 0.3, 0]

             

