base_config: ../config/
base_expid: AFN_base
dataset_id: criteo_x4_9ea3bdfc

dataset_config:
    criteo_x4_9ea3bdfc:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_9ea3bdfc/train.h5
        valid_data: ../data/Criteo/criteo_x4_9ea3bdfc/valid.h5
        test_data: ../data/Criteo/criteo_x4_9ea3bdfc/test.h5

tuner_space:
    model_root: './Criteo/AFN_criteo/min10/'
    embedding_regularizer: [1.e-5, 1.e-4]
    embedding_dim: 16
    logarithmic_neurons: [1200, 1500]
    afn_hidden_units: [[1000, 1000, 1000, 1000]]
    afn_activations: relu
    afn_dropout: 0.2
    ensemble_dnn: True
    dnn_hidden_units: [[1000, 1000, 1000, 1000], [1000, 1000, 1000, 1000, 1000]]
    dnn_activations: relu
    dnn_dropout: [0, 0.1, 0.2]
    batch_norm: True
    batch_size: 10000
    seed: 2019

