base_config: ../config/
base_expid: DCN_kkbox_x4

dataset_config:
    kkbox_x4:
        data_root: ../data/KKBox/
        data_format: csv
        train_data: ../data/KKBox/KKBox_x4/train.csv
        valid_data: ../data/KKBox/KKBox_x4/valid.csv
        test_data: ../data/KKBox/KKBox_x4/test.csv
        min_categr_count: 10
        feature_cols:
            - {name: ["msno","song_id","source_system_tab","source_screen_name","source_type","city","gender",
                      "registered_via","language"], active: True, dtype: str, type: categorical}
            - {name: genre_ids, active: True, dtype: str, type: sequence, max_len: 3, encoder: MaskedSumPooling}
            - {name: artist_name, active: True, dtype: str, type: sequence, max_len: 3, encoder: MaskedSumPooling}
            - {name: isrc, active: True, dtype: str, type: categorical, preprocess: extract_country_code}
            - {name: bd, active: True, dtype: str, type: categorical, preprocess: bucketize_age}
        label_col: {name: label, dtype: float}

tuner_space:
    model_root: './KKBox/DCN_kkbox/'
    embedding_dim: 128
    dnn_hidden_units: [[5000, 5000], [1000, 1000, 1000], [2000, 2000, 2000], [5000, 5000, 5000]]
    crossing_layers: [3, 4]
    embedding_regularizer: 5.e-4
    net_dropout: [0.3, 0.4, 0.5]
    learning_rate: 0.001
    batch_size: 10000
    seed: 2019
    
