base_config: ../config/
base_expid: CCPM_base
dataset_id: criteo_x4_5c863b0f

dataset_config:
    criteo_x4_5c863b0f:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_5c863b0f/train.h5
        valid_data: ../data/Criteo/criteo_x4_5c863b0f/valid.h5
        test_data: ../data/Criteo/criteo_x4_5c863b0f/test.h5

tuner_space:
    model_root: './Criteo/CCPM_criteo/min10/'
    embedding_dim: 16
    embedding_regularizer: [1.e-6, 1.e-5]
    batch_size: 10000
    learning_rate: 1.e-3
    channels: [[16, 32, 64], [32, 64, 128], [64, 128, 256], [128, 256, 512], [256, 512, 1024]]
    kernel_heights: [[7, 5, 3]]
    seed: 2019
   
