base_config: ../config/
base_expid: AutoInt_base
dataset_id: avazu_x4_3bbbc4c9

dataset_config:
    avazu_x4_3bbbc4c9:
        data_format: h5
        data_root: '../data/Avazu/'
        train_data: ../data/Avazu/avazu_x4_3bbbc4c9/train.h5
        valid_data: ../data/Avazu/avazu_x4_3bbbc4c9/valid.h5
        test_data: ../data/Avazu/avazu_x4_3bbbc4c9/test.h5

tuner_space:
    model_root: './Avazu/AutoInt_avazu/min2/'
    embedding_dim: 16
    learning_rate: 1.e-3
    dnn_hidden_units: [[]]
    embedding_regularizer: [0, 1.e-8, 1.e-6]
    net_dropout: 0
    num_heads: 1
    attention_layers: [5, 6, 7]
    attention_dim: [64, 128]
    use_residual: [True, False]
    batch_norm: False
    layer_norm: False
    use_scale: False
    use_wide: [False, True]
    batch_size: 10000
    seed: 2019
