ONN_kkbox_x1_001_105b4cb0:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ONN
    model_id: ONN_base
    model_root: ./Avazu/ONN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
ONN_kkbox_x1_002_ee307b3a:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500, 500]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ONN
    model_id: ONN_base
    model_root: ./Avazu/ONN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
ONN_kkbox_x1_003_1f25e669:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [2000, 2000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ONN
    model_id: ONN_base
    model_root: ./Avazu/ONN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
ONN_kkbox_x1_004_22ca11b1:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500, 500, 500]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ONN
    model_id: ONN_base
    model_root: ./Avazu/ONN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
ONN_kkbox_x1_005_0a024c86:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ONN
    model_id: ONN_base
    model_root: ./Avazu/ONN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
ONN_kkbox_x1_006_f9e1aff9:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500, 500]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ONN
    model_id: ONN_base
    model_root: ./Avazu/ONN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
ONN_kkbox_x1_007_fe75a621:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [2000, 2000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ONN
    model_id: ONN_base
    model_root: ./Avazu/ONN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
ONN_kkbox_x1_008_d8ef7764:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.0005
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500, 500, 500]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ONN
    model_id: ONN_base
    model_root: ./Avazu/ONN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
ONN_kkbox_x1_009_d0b7a89a:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ONN
    model_id: ONN_base
    model_root: ./Avazu/ONN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
ONN_kkbox_x1_010_943d58f7:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500, 500]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ONN
    model_id: ONN_base
    model_root: ./Avazu/ONN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
ONN_kkbox_x1_011_31d50cb5:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [2000, 2000]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ONN
    model_id: ONN_base
    model_root: ./Avazu/ONN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
ONN_kkbox_x1_012_c959a907:
    batch_norm: false
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: 128
    embedding_dropout: 0
    embedding_regularizer: 0.001
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [500, 500, 500, 500]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: ONN
    model_id: ONN_base
    model_root: ./Avazu/ONN_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
