base_config: ../config/
base_expid: AutoInt_avazu_x4

dataset_config:
    avazu_x4_001_d45ad60e:
        data_format: h5
        data_root: '../data/Avazu/'
        train_data: ../data/Avazu/avazu_x4_001_d45ad60e/train.h5
        valid_data: ../data/Avazu/avazu_x4_001_d45ad60e/valid.h5
        test_data: ../data/Avazu/avazu_x4_001_d45ad60e/test.h5

tuner_space:
    model_root: './Avazu/AutoInt_avazu/'
    embedding_dim: 40
    learning_rate: 1.e-3
    dnn_hidden_units: [[1000, 1000, 1000]]
    embedding_regularizer: 1.0e-08
    net_dropout: 0
    num_heads: 1
    attention_layers: 3
    attention_dim: 64
    use_residual: True
    batch_norm: False
    layer_norm: False
    use_scale: False
    use_wide: False
    batch_size: 10000
    seed: [658895, 382107, 2019]
