base_config: ../config/
base_expid: FLEN_base
dataset_id: avazu_x4

dataset_config:
  avazu_x4:
      data_root: ../data/Avazu/
      data_format: csv
      train_data: ../data/Avazu/Avazu_x4/train.csv
      valid_data: ../data/Avazu/Avazu_x4/valid.csv
      test_data: ../data/Avazu/Avazu_x4/test.csv
      min_categr_count: 2
      feature_cols:
          - {name: id, active: False, dtype: str, type: categorical, source: context}
          - {name: hour, active: True, dtype: str, type: categorical, preprocess: convert_hour, source: context}
          - {name: [C1,C14,C15,C16,C17,C18,C19,C20,C21,device_id,device_ip,device_model,device_type], active: True, dtype: str, 
             type: categorical, source: user}
          - {name: [banner_pos,site_id,site_domain,site_category,device_conn_type], active: True, dtype: str, type: categorical, source: context}
          - {name: [app_id,app_domain,app_category], active: True, dtype: str, type: categorical, source: item}
          - {name: weekday, active: True, dtype: str, type: categorical, preprocess: convert_weekday, source: context}
          - {name: weekend, active: True, dtype: str, type: categorical, preprocess: convert_weekend, source: context}
      label_col: {name: click, dtype: float}

tuner_space:
    model_root: './Avazu/FLEN_avazu/min2/'
    embedding_dim: 16
    embedding_regularizer: [0, 1.e-9, 1.e-8]
    dnn_hidden_units: [[1000, 1000, 1000], [1000, 1000, 1000, 1000], [2000, 2000, 2000, 2000]]
    net_dropout: 0
    learning_rate: 1.e-3
    batch_size: 10000
    seed: 2019

