DCN_criteo_x1_001_8d74d396:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 4
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_002_8b99a9b2:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 5
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_003_10b20de3:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 6
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_004_1d1f20d0:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 7
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_005_88ac8da2:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 8
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_006_24b33fc1:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 9
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-06
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_007_708638f6:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 4
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_008_49141c1c:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 5
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_009_31f31d10:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 6
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_010_1dfa9ac6:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 7
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_011_1b232807:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 8
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_012_32e10ead:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 9
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_013_515ae8ce:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 4
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_014_d2502aa3:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 5
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_015_21e33515:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 6
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_016_69de95ec:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 7
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_017_25e83a03:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 8
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DCN_criteo_x1_018_4f79b650:
    batch_norm: false
    batch_size: 4096
    crossing_layers: 9
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    dnn_hidden_units: null
    embedding_dim: 10
    embedding_regularizer: 0.0001
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DCN
    model_id: DCN_base
    model_root: ./Criteo/DCN_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
