base_config: ../config/
base_expid: HOFM_base
dataset_id: avazu_x4_3bbbc4c9

dataset_config:
    avazu_x4_3bbbc4c9:
        data_format: h5
        data_root: '../data/Avazu/'
        train_data: ../data/Avazu/avazu_x4_3bbbc4c9/train.h5
        valid_data: ../data/Avazu/avazu_x4_3bbbc4c9/valid.h5
        test_data: ../data/Avazu/avazu_x4_3bbbc4c9/test.h5

tuner_space:
    model_root: './Avazu/HOFM_avazu/min2/'
    regularizer: [1.0e-07, 1.0e-08, 0]
    embedding_dim: [[16, 16], [16, 8]]
    order: 3
    reuse_embedding: False
    batch_size: 10000
    seed: 2019

