base_config: ../config/
base_expid: HOFM_base
dataset_id: criteo_x4_5c863b0f

dataset_config:
    criteo_x4_5c863b0f:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_5c863b0f/train.h5
        valid_data: ../data/Criteo/criteo_x4_5c863b0f/valid.h5
        test_data: ../data/Criteo/criteo_x4_5c863b0f/test.h5

tuner_space:
    model_root: './Criteo/HOFM_criteo/min10/'
    regularizer: [1.0e-05, 1.0e-06]
    embedding_dim: [[16, 16], [16, 8], [16, 4]]
    order: 3
    reuse_embedding: False
    batch_size: 3000
    seed: 2019

