base_config: ../config/
base_expid: DeepCrossing_criteo_x4

dataset_config:
    criteo_x4_001_be98441d:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_001_be98441d/train.h5
        valid_data: ../data/Criteo/criteo_x4_001_be98441d/valid.h5
        test_data: ../data/Criteo/criteo_x4_001_be98441d/test.h5

tuner_space:
    model_root: './Criteo/DeepCrossing_criteo/'
    embedding_dim: 40
    learning_rate: 1.e-3
    residual_blocks: [[5000, 5000], [1000, 1000, 1000], [3000, 3000, 3000], [5000, 5000, 5000],
                      [1000, 1000, 1000, 1000], [3000, 3000, 3000, 3000], [5000, 5000, 5000, 5000]]
    net_dropout: [0, 0.1]
    embedding_regularizer: ['l2(1.e-6)', 'l2(1.e-5)', 'l2(1.e-4)']
    batch_size: 10000
    seed: 2019
    batch_norm: [False, True]
    use_residual: True
