base_config: ../config/
base_expid: FwFM_base
dataset_id: criteo_x4_9ea3bdfc

dataset_config:
    criteo_x4_9ea3bdfc:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_9ea3bdfc/train.h5
        valid_data: ../data/Criteo/criteo_x4_9ea3bdfc/valid.h5
        test_data: ../data/Criteo/criteo_x4_9ea3bdfc/test.h5

tuner_space:
    model_root: './Criteo/FwFM_criteo_x4_001/'
    embedding_dim: 16
    regularizer: [5.e-6, 1.e-5, 5.e-5]
    linear_type: [FiLV, LW]
    learning_rate: 1.e-3
    batch_size: 10000
    seed: 2019

