base_config: ../config/
base_expid: xDeepFM_base
dataset_id: criteo_x4_5c863b0f

dataset_config:
    criteo_x4_5c863b0f:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_5c863b0f/train.h5
        valid_data: ../data/Criteo/criteo_x4_5c863b0f/valid.h5
        test_data: ../data/Criteo/criteo_x4_5c863b0f/test.h5

tuner_space:
    model_root: './Criteo/CIN_criteo/min10/'
    embedding_dim: 16
    learning_rate: 1.e-3
    dnn_hidden_units: [[]]
    cin_layer_units: [[128, 128, 128], [256, 256, 256], [64, 64, 64, 64], [128, 128, 128, 128],
                      [256, 256, 256, 256]]
    net_dropout: [0, 0.1, 0.2]
    embedding_regularizer: [1.e-5, 1.e-6]
    batch_size: 10000
    seed: 2019

