base_config: ../config/
base_expid: FGCNN_base
dataset_id: criteo_x4_5c863b0f

dataset_config:
    criteo_x4_5c863b0f:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_5c863b0f/train.h5
        valid_data: ../data/Criteo/criteo_x4_5c863b0f/valid.h5
        test_data: ../data/Criteo/criteo_x4_5c863b0f/test.h5

tuner_space:
    model_root: './Criteo/FGCNN_criteo_x4_001/'
    embedding_dim: 16
    share_embedding: False
    embedding_regularizer: [1.e-5, 1.e-6, 1.e-7]
    net_dropout: [0, 0.1]
    channels: [[38, 40, 42, 44]]
    kernel_heights: 9
    pooling_sizes: 2
    recombined_channels: 3
    conv_activation: Tanh
    conv_batch_norm: True
    dnn_hidden_units: [[1000, 1000, 1000], [1000, 1000, 1000, 1000], [1000, 1000, 1000, 1000, 1000]]
    dnn_batch_norm: False
    learning_rate: 1.e-3
    batch_size: 5000
    seed: 2019
