base_config: ../config/
base_expid: AutoInt_kkbox_x4

dataset_config:
    kkbox_x4_001_c5c9c6e3:
        data_format: h5
        data_root: '../data/KKBox/'
        train_data: ../data/KKBox/kkbox_x4_001_c5c9c6e3/train.h5
        valid_data: ../data/KKBox/kkbox_x4_001_c5c9c6e3/valid.h5
        test_data: ../data/KKBox/kkbox_x4_001_c5c9c6e3/test.h5

tuner_space:
    model_root: './KKBox/AutoInt_kkbox/'
    embedding_dim: 128
    dnn_hidden_units: [[]]
    embedding_regularizer: 5.e-4
    net_dropout: 0
    num_heads: 2
    attention_layers: 5
    attention_dim: 256
    learning_rate: 0.001
    use_residual: [True, False]
    batch_norm: False
    layer_norm: [True, False]
    use_scale: False
    use_wide: [True, False]
    batch_size: 10000
    seed: 2019




   