base_config: ../config/
base_setting: FM_criteo_x4

tuner_space:
    model_dir: './Criteo/'
    min_categr_count: 2
    embedding_dim: 40
    regularizer: [0, 'l2(1.e-9)', 'l2(1.e-8)', 'l2(1.e-7)', 'l2(1.e-6)']
    learning_rate: 1.e-3
    batch_size: 10000
    seed: 2019


