base_config: ../config/
base_expid: xDeepFM_criteo_x4
dataset_id: criteo_x4_001_be98441d

dataset_config:
    criteo_x4_001_be98441d:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_001_be98441d/train.h5
        valid_data: ../data/Criteo/criteo_x4_001_be98441d/valid.h5
        test_data: ../data/Criteo/criteo_x4_001_be98441d/test.h5

tuner_space:
    model_root: './Criteo/xDeepFM_criteo/'
    embedding_dim: 40
    learning_rate: 1.e-3
    dnn_hidden_units: [[]]
    cin_layer_units: [[39, 39], [39, 39, 39], [39, 39, 39, 39], 
                      [100, 100], [100, 100, 100], [100, 100, 100, 100],
                      [200, 200], [200, 200, 200], [200, 200, 200, 200]]
    embedding_regularizer: [1.e-5, 1.e-6]
    batch_size: 2000
    seed: 2019
