base_config: ../config/
base_expid: HOFM_criteo_x4

dataset_config:
    criteo_x4_001_be98441d:
        data_format: h5
        data_root: '../data/Criteo/'
        train_data: ../data/Criteo/criteo_x4_001_be98441d/train.h5
        valid_data: ../data/Criteo/criteo_x4_001_be98441d/valid.h5
        test_data: ../data/Criteo/criteo_x4_001_be98441d/test.h5

tuner_space:
    model_root: './Criteo/HOFM_criteo/'
    regularizer: [1.e-5, 1.e-6, 1.e-8, 0]
    batch_size: 3000
    embedding_dim: [[40, 5]]
    order: 3
    reuse_embedding: False
    seed: 2019

