base_config: ../config/
base_expid: HOFM_avazu_x4

dataset_config:
    avazu_x4_001_d45ad60e:
        data_format: h5
        data_root: '../data/Avazu/'
        train_data: ../data/Avazu/avazu_x4_001_d45ad60e/train.h5
        valid_data: ../data/Avazu/avazu_x4_001_d45ad60e/valid.h5
        test_data: ../data/Avazu/avazu_x4_001_d45ad60e/test.h5

tuner_space:
    model_root: './Avazu/HOFM_avazu/'
    regularizer: [0, 1.e-6, 1.e-7, 1.e-8]
    batch_size: 5000
    embedding_dim: [[40, 5], [40, 8], [40, 10]]
    order: 3
    reuse_embedding: False
    seed: 2019
    patience: 2

